# Generated by Django 4.2.5 on 2023-09-29 07:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_guest_email_remove_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='product_images/'),
        ),
    ]
