# Generated by Django 4.2.5 on 2023-10-02 08:36

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='graphics')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
