# Generated by Django 4.2.5 on 2023-10-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_graphic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
