# Generated by Django 4.2.5 on 2023-10-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending to confirm', 'Pending to confirm'), ('Waiting for arrival', 'Waiting for arrival'), ('Waiting to be delivered', 'Waiting to be delivered'), ('On delivery vehicle', 'On delivery vehicle'), ('Delivered', 'Delivered')], default='Pending to confirm', max_length=30),
        ),
    ]
