# Generated by Django 4.2.5 on 2023-10-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='confirm',
        ),
    ]
