# Generated by Django 4.2.5 on 2023-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_orderitem_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accpeted_terms',
            field=models.BooleanField(default=False, verbose_name='read and accepted terms and conditions'),
        ),
    ]
