# Generated by Django 4.2.5 on 2023-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_accpeted_terms_order_accepted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='link',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="What's your name?"),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_phone_number',
            field=models.TextField(blank=True, null=True, verbose_name="What's your phone number?"),
        ),
    ]
