# Generated by Django 4.2.5 on 2023-10-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.AddField(
            model_name='color',
            name='hex',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
